### PR TITLE
Feature/zip ignore formats

### PR DESCRIPTION
**Pull request by JamesVarndell**
Change to make it possible to ignore specific files by name/wildcard when opening ZIP files with emohawk.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf-projects/emohawk?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-projects/emohawk?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-projects/emohawk?pullRequest=8) it.</sub>

**Review by EddyCMWF — COMMENTED** [review]
Should we also update the syntax to the DirectoryReader whilst we're on this:
https://github.com/ecmwf-projects/emohawk/blob/82ec6463be4f2688a193864f29d6f1480da6d641/emohawk/readers/directory.py#L20-L40

**Review by EddyCMWF — CHANGES_REQUESTED** [review]
Please can you add a test before merging

**Comment by JamesVarndell** [comment]
Thanks @EddyCMWF, tests added.

**Review by EddyCMWF — APPROVED** [review]

**Pull request merged**
